import { FormEvent, ReactNode, useEffect, useMemo, useState } from 'react';
import { Building2, FilePlus2, Gauge, Pencil, Plus, Search, Store, Users, X } from 'lucide-react';
import { api } from './api';

type Building={id:number;name:string};
type Space={id:number;buildingId:number;buildingName:string;code:string;location:string;description?:string;totalAreaM2:number;status:'AVAILABLE'|'LEASED'|'INACTIVE'};
type Tenant={id:number;code:string;name:string;taxCode?:string};
type Contract={id:number;contractNumber:string;spaceId:number;spaceCode:string;location:string;tenantId:number;tenantName:string;leasedAreaM2:number;unitPricePerM2:number;vatRate:number;monthlyTotal:number;startDate:string;endDate:string;paymentDay:number;status:string};
type Meter={id:number;spaceId:number;spaceCode:string;meterCode:string;description?:string;defaultUnitPrice:number;active:boolean};
type Reading={id:number;meterId:number;meterCode:string;spaceCode:string;periodCode:string;previousIndex:number;currentIndex:number;consumption:number;unitPrice:number;amount:number;readingDate:string};
type Dialog='space'|'tenant'|'contract'|'meter'|'reading'|null;
const money=(value:number)=>new Intl.NumberFormat('vi-VN').format(value)+' đ';
const today=new Date().toISOString().slice(0,10), period=today.slice(0,7);

export function CommercialPage(){
  const [tab,setTab]=useState<'spaces'|'contracts'|'electric'>('spaces');
  const [buildings,setBuildings]=useState<Building[]>([]),[spaces,setSpaces]=useState<Space[]>([]),[tenants,setTenants]=useState<Tenant[]>([]),[contracts,setContracts]=useState<Contract[]>([]),[meters,setMeters]=useState<Meter[]>([]),[readings,setReadings]=useState<Reading[]>([]);
  const [dialog,setDialog]=useState<Dialog>(null),[editingSpace,setEditingSpace]=useState<Space|null>(null),[error,setError]=useState(''),[saving,setSaving]=useState(false),[keyword,setKeyword]=useState('');
  const [spaceForm,setSpaceForm]=useState({buildingId:'',code:'',location:'',description:'',totalAreaM2:'',status:'AVAILABLE'});
  const [tenantForm,setTenantForm]=useState({code:'',name:'',taxCode:'',representative:'',phone:'',email:'',billingAddress:''});
  const [contractForm,setContractForm]=useState({contractNumber:'',spaceId:'',tenantId:'',leasedAreaM2:'',unitPricePerM2:'',vatRate:'10',depositAmount:'0',startDate:today,endDate:'',paymentDay:'5',status:'ACTIVE',notes:''});
  const [meterForm,setMeterForm]=useState({spaceId:'',meterCode:'',description:'',defaultUnitPrice:''});
  const [readingForm,setReadingForm]=useState({meterId:'',periodCode:period,previousIndex:'',currentIndex:'',unitPrice:'',readingDate:today,imageUrl:'',note:''});

  async function load(){try{setError('');const [b,s,t,c,m,r]=await Promise.all([api<Building[]>('/buildings'),api<Space[]>('/commercial/spaces'),api<Tenant[]>('/commercial/tenants'),api<Contract[]>('/commercial/contracts'),api<Meter[]>('/commercial/meters'),api<Reading[]>('/commercial/readings')]);setBuildings(b);setSpaces(s);setTenants(t);setContracts(c);setMeters(m);setReadings(r);}catch(e){setError(e instanceof Error?e.message:'Không tải được dữ liệu.')}}
  useEffect(()=>{load()},[]);
  const visibleSpaces=useMemo(()=>spaces.filter(s=>!keyword.trim()||`${s.code} ${s.location}`.toLowerCase().includes(keyword.toLowerCase())),[spaces,keyword]);
  const rentedArea=contracts.filter(c=>c.status==='ACTIVE').reduce((n,c)=>n+Number(c.leasedAreaM2),0);

  function openSpace(s?:Space){setEditingSpace(s??null);setSpaceForm(s?{buildingId:String(s.buildingId),code:s.code,location:s.location,description:s.description??'',totalAreaM2:String(s.totalAreaM2),status:s.status}:{buildingId:String(buildings[0]?.id??''),code:'',location:'',description:'',totalAreaM2:'',status:'AVAILABLE'});setDialog('space');setError('')}
  function openContract(){setContractForm({...contractForm,spaceId:String(spaces.find(s=>s.status!=='INACTIVE')?.id??''),tenantId:String(tenants[0]?.id??'')});setDialog('contract');setError('')}
  function openMeter(){setMeterForm({spaceId:String(spaces.find(s=>s.status!=='INACTIVE')?.id??''),meterCode:'',description:'',defaultUnitPrice:''});setDialog('meter');setError('')}
  function openReading(){const m=meters.find(x=>x.active);setReadingForm({meterId:String(m?.id??''),periodCode:period,previousIndex:'',currentIndex:'',unitPrice:String(m?.defaultUnitPrice??''),readingDate:today,imageUrl:'',note:''});setDialog('reading');setError('')}
  async function submit(path:string,body:unknown,method='POST'){setSaving(true);setError('');try{await api(path,{method,body:JSON.stringify(body)});setDialog(null);setEditingSpace(null);await load()}catch(e){setError(e instanceof Error?e.message:'Không thể lưu dữ liệu.')}finally{setSaving(false)}}

  return <>
    <header><div><h1>Mặt bằng kinh doanh và điện</h1><p>Quản lý độc lập theo vị trí, diện tích thuê, hợp đồng và công tơ riêng</p></div></header>
    <section className="unit-summary commercial-summary"><article><Store/><span><b>{spaces.length}</b><small>Tổng mặt bằng</small></span></article><article><Building2/><span><b>{rentedArea.toLocaleString('vi-VN')} m²</b><small>Diện tích đang tính tiền</small></span></article><article><Users/><span><b>{tenants.length}</b><small>Doanh nghiệp thuê</small></span></article><article><Gauge/><span><b>{meters.filter(m=>m.active).length}</b><small>Công tơ đang dùng</small></span></article></section>
    <div className="tabs"><button className={tab==='spaces'?'active':''} onClick={()=>setTab('spaces')}>Mặt bằng</button><button className={tab==='contracts'?'active':''} onClick={()=>setTab('contracts')}>Hợp đồng thuê</button><button className={tab==='electric'?'active':''} onClick={()=>setTab('electric')}>Điện công tơ</button></div>
    {error&&<div className="page-error top-error">{error}</div>}

    {tab==='spaces'&&<section className="panel unit-panel"><div className="toolbar"><label className="search"><Search/><input value={keyword} onChange={e=>setKeyword(e.target.value)} placeholder="Tìm mã hoặc vị trí..."/></label><span className="toolbar-spacer"/><button className="secondary" onClick={()=>{setTenantForm({code:'',name:'',taxCode:'',representative:'',phone:'',email:'',billingAddress:''});setDialog('tenant')}}><Users/>Thêm khách thuê</button><button className="primary" onClick={()=>openSpace()}><Plus/>Thêm mặt bằng</button></div><div className="table-wrap"><table><thead><tr><th>Mã</th><th>Tòa nhà</th><th>Vị trí/phạm vi</th><th>Diện tích</th><th>Trạng thái</th><th/></tr></thead><tbody>{visibleSpaces.length===0?<tr><td colSpan={6} className="empty">Chưa có mặt bằng kinh doanh.</td></tr>:visibleSpaces.map(s=><tr key={s.id}><td><b>{s.code}</b></td><td>{s.buildingName}</td><td>{s.location}<small className="cell-note">{s.description}</small></td><td>{s.totalAreaM2} m²</td><td><span className={`status ${s.status.toLowerCase()}`}>{s.status==='AVAILABLE'?'Còn trống':s.status==='LEASED'?'Đang thuê':'Ngừng'}</span></td><td className="actions"><button onClick={()=>openSpace(s)}><Pencil/></button></td></tr>)}</tbody></table></div></section>}

    {tab==='contracts'&&<section className="panel unit-panel"><div className="toolbar"><span className="section-hint">Giá thuê được tính theo diện tích ghi trên từng hợp đồng.</span><span className="toolbar-spacer"/><button className="secondary" onClick={()=>{setTenantForm({code:'',name:'',taxCode:'',representative:'',phone:'',email:'',billingAddress:''});setDialog('tenant')}}><Users/>Khách thuê</button><button className="primary" disabled={!spaces.length||!tenants.length} onClick={openContract}><FilePlus2/>Lập hợp đồng</button></div><div className="table-wrap"><table><thead><tr><th>Số hợp đồng</th><th>Khách thuê</th><th>Mặt bằng</th><th>Diện tích × đơn giá</th><th>Thành tiền/tháng</th><th>Thời hạn</th><th>Trạng thái</th></tr></thead><tbody>{contracts.length===0?<tr><td colSpan={7} className="empty">Chưa có hợp đồng thuê.</td></tr>:contracts.map(c=><tr key={c.id}><td><b>{c.contractNumber}</b></td><td>{c.tenantName}</td><td>{c.spaceCode}<small className="cell-note">{c.location}</small></td><td>{c.leasedAreaM2} m² × {money(c.unitPricePerM2)}</td><td><b>{money(c.monthlyTotal)}</b><small className="cell-note">VAT {c.vatRate}%</small></td><td>{c.startDate}<small className="cell-note">đến {c.endDate}</small></td><td><span className={`status ${c.status.toLowerCase()}`}>{c.status==='ACTIVE'?'Hiệu lực':c.status}</span></td></tr>)}</tbody></table></div></section>}

    {tab==='electric'&&<section className="panel unit-panel"><div className="toolbar"><span className="section-hint">Mỗi mặt bằng có thể có một hoặc nhiều công tơ riêng.</span><span className="toolbar-spacer"/><button className="secondary" disabled={!spaces.length} onClick={openMeter}><Gauge/>Thêm công tơ</button><button className="primary" disabled={!meters.length} onClick={openReading}><Plus/>Ghi chỉ số</button></div><div className="table-wrap"><table><thead><tr><th>Kỳ</th><th>Công tơ</th><th>Mặt bằng</th><th>Chỉ số đầu → cuối</th><th>Tiêu thụ</th><th>Đơn giá</th><th>Thành tiền</th></tr></thead><tbody>{readings.length===0?<tr><td colSpan={7} className="empty">Chưa có chỉ số điện. Hãy tạo công tơ và ghi kỳ đầu tiên.</td></tr>:readings.map(r=><tr key={r.id}><td><b>{r.periodCode}</b></td><td>{r.meterCode}</td><td>{r.spaceCode}</td><td>{r.previousIndex} → {r.currentIndex}</td><td>{r.consumption} kWh</td><td>{money(r.unitPrice)}</td><td><b>{money(r.amount)}</b></td></tr>)}</tbody></table></div></section>}

    {dialog==='space'&&<Modal title={editingSpace?'Cập nhật mặt bằng':'Thêm mặt bằng kinh doanh'} note="Mặt bằng không cần liên kết với căn hộ." close={()=>setDialog(null)} saving={saving} onSubmit={e=>{e.preventDefault();submit(editingSpace?`/commercial/spaces/${editingSpace.id}`:'/commercial/spaces',{...spaceForm,buildingId:Number(spaceForm.buildingId),totalAreaM2:Number(spaceForm.totalAreaM2)},editingSpace?'PUT':'POST')}}><label>Tòa nhà<select required value={spaceForm.buildingId} onChange={e=>setSpaceForm({...spaceForm,buildingId:e.target.value})}>{buildings.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Mã mặt bằng<input required value={spaceForm.code} onChange={e=>setSpaceForm({...spaceForm,code:e.target.value})} placeholder="MB-A-01"/></label><label>Vị trí/phạm vi<input required value={spaceForm.location} onChange={e=>setSpaceForm({...spaceForm,location:e.target.value})} placeholder="Tầng 1 – khu phía Đông"/></label><label>Tổng diện tích (m²)<input required type="number" min="0.01" step="0.01" value={spaceForm.totalAreaM2} onChange={e=>setSpaceForm({...spaceForm,totalAreaM2:e.target.value})}/></label><label className="full">Mô tả khu vực<textarea value={spaceForm.description} onChange={e=>setSpaceForm({...spaceForm,description:e.target.value})} placeholder="Toàn bộ sàn hoặc các phòng được ghép..."/></label>{editingSpace&&<label>Trạng thái<select value={spaceForm.status} onChange={e=>setSpaceForm({...spaceForm,status:e.target.value})}><option value="AVAILABLE">Còn trống</option><option value="LEASED">Đang thuê</option><option value="INACTIVE">Ngừng hoạt động</option></select></label>}</Modal>}

    {dialog==='tenant'&&<Modal title="Thêm doanh nghiệp thuê" note="Thông tin dùng cho hợp đồng và xuất hóa đơn." close={()=>setDialog(null)} saving={saving} onSubmit={e=>{e.preventDefault();submit('/commercial/tenants',tenantForm)}}><label>Mã khách thuê<input required value={tenantForm.code} onChange={e=>setTenantForm({...tenantForm,code:e.target.value})} placeholder="KH-001"/></label><label>Tên doanh nghiệp<input required value={tenantForm.name} onChange={e=>setTenantForm({...tenantForm,name:e.target.value})}/></label><label>Mã số thuế<input value={tenantForm.taxCode} onChange={e=>setTenantForm({...tenantForm,taxCode:e.target.value})}/></label><label>Người đại diện<input value={tenantForm.representative} onChange={e=>setTenantForm({...tenantForm,representative:e.target.value})}/></label><label>Điện thoại<input value={tenantForm.phone} onChange={e=>setTenantForm({...tenantForm,phone:e.target.value})}/></label><label>Email<input type="email" value={tenantForm.email} onChange={e=>setTenantForm({...tenantForm,email:e.target.value})}/></label><label className="full">Địa chỉ xuất hóa đơn<input value={tenantForm.billingAddress} onChange={e=>setTenantForm({...tenantForm,billingAddress:e.target.value})}/></label></Modal>}

    {dialog==='contract'&&<Modal title="Lập hợp đồng thuê" note="Tiền thuê tháng = diện tích tính tiền × đơn giá/m² + VAT." close={()=>setDialog(null)} saving={saving} onSubmit={e=>{e.preventDefault();submit('/commercial/contracts',{...contractForm,spaceId:Number(contractForm.spaceId),tenantId:Number(contractForm.tenantId),leasedAreaM2:Number(contractForm.leasedAreaM2),unitPricePerM2:Number(contractForm.unitPricePerM2),vatRate:Number(contractForm.vatRate),depositAmount:Number(contractForm.depositAmount),paymentDay:Number(contractForm.paymentDay)})}}><label>Số hợp đồng<input required value={contractForm.contractNumber} onChange={e=>setContractForm({...contractForm,contractNumber:e.target.value})}/></label><label>Khách thuê<select required value={contractForm.tenantId} onChange={e=>setContractForm({...contractForm,tenantId:e.target.value})}>{tenants.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Mặt bằng<select required value={contractForm.spaceId} onChange={e=>setContractForm({...contractForm,spaceId:e.target.value})}>{spaces.filter(s=>s.status!=='INACTIVE').map(s=><option key={s.id} value={s.id}>{s.code} – {s.location}</option>)}</select></label><label>Diện tích tính tiền (m²)<input required type="number" min="0.01" step="0.01" value={contractForm.leasedAreaM2} onChange={e=>setContractForm({...contractForm,leasedAreaM2:e.target.value})}/></label><label>Đơn giá/m²/tháng<input required type="number" min="0" value={contractForm.unitPricePerM2} onChange={e=>setContractForm({...contractForm,unitPricePerM2:e.target.value})}/></label><label>VAT (%)<input required type="number" min="0" max="100" value={contractForm.vatRate} onChange={e=>setContractForm({...contractForm,vatRate:e.target.value})}/></label><label>Ngày bắt đầu<input required type="date" value={contractForm.startDate} onChange={e=>setContractForm({...contractForm,startDate:e.target.value})}/></label><label>Ngày kết thúc<input required type="date" value={contractForm.endDate} onChange={e=>setContractForm({...contractForm,endDate:e.target.value})}/></label><label>Ngày đến hạn hàng tháng<input required type="number" min="1" max="28" value={contractForm.paymentDay} onChange={e=>setContractForm({...contractForm,paymentDay:e.target.value})}/></label><label>Tiền đặt cọc<input required type="number" min="0" value={contractForm.depositAmount} onChange={e=>setContractForm({...contractForm,depositAmount:e.target.value})}/></label></Modal>}

    {dialog==='meter'&&<Modal title="Thêm công tơ điện" note="Công tơ được gắn trực tiếp với mặt bằng kinh doanh." close={()=>setDialog(null)} saving={saving} onSubmit={e=>{e.preventDefault();submit('/commercial/meters',{...meterForm,spaceId:Number(meterForm.spaceId),defaultUnitPrice:Number(meterForm.defaultUnitPrice)})}}><label>Mặt bằng<select required value={meterForm.spaceId} onChange={e=>setMeterForm({...meterForm,spaceId:e.target.value})}>{spaces.filter(s=>s.status!=='INACTIVE').map(s=><option key={s.id} value={s.id}>{s.code} – {s.location}</option>)}</select></label><label>Mã công tơ<input required value={meterForm.meterCode} onChange={e=>setMeterForm({...meterForm,meterCode:e.target.value})}/></label><label>Đơn giá điện mặc định<input required type="number" min="0" value={meterForm.defaultUnitPrice} onChange={e=>setMeterForm({...meterForm,defaultUnitPrice:e.target.value})}/></label><label>Mô tả<input value={meterForm.description} onChange={e=>setMeterForm({...meterForm,description:e.target.value})}/></label></Modal>}

    {dialog==='reading'&&<Modal title="Ghi chỉ số công tơ" note="Hệ thống tự tính sản lượng và thành tiền." close={()=>setDialog(null)} saving={saving} onSubmit={e=>{e.preventDefault();submit('/commercial/readings',{...readingForm,meterId:Number(readingForm.meterId),previousIndex:Number(readingForm.previousIndex),currentIndex:Number(readingForm.currentIndex),unitPrice:Number(readingForm.unitPrice)})}}><label>Công tơ<select required value={readingForm.meterId} onChange={e=>{const m=meters.find(x=>x.id===Number(e.target.value));setReadingForm({...readingForm,meterId:e.target.value,unitPrice:String(m?.defaultUnitPrice??'')})}}>{meters.filter(m=>m.active).map(m=><option key={m.id} value={m.id}>{m.meterCode} – {m.spaceCode}</option>)}</select></label><label>Kỳ ghi điện<input required type="month" value={readingForm.periodCode} onChange={e=>setReadingForm({...readingForm,periodCode:e.target.value})}/></label><label>Chỉ số đầu<input required type="number" min="0" step="0.001" value={readingForm.previousIndex} onChange={e=>setReadingForm({...readingForm,previousIndex:e.target.value})}/></label><label>Chỉ số cuối<input required type="number" min="0" step="0.001" value={readingForm.currentIndex} onChange={e=>setReadingForm({...readingForm,currentIndex:e.target.value})}/></label><label>Đơn giá điện<input required type="number" min="0" value={readingForm.unitPrice} onChange={e=>setReadingForm({...readingForm,unitPrice:e.target.value})}/></label><label>Ngày ghi<input required type="date" value={readingForm.readingDate} onChange={e=>setReadingForm({...readingForm,readingDate:e.target.value})}/></label></Modal>}
  </>;
}

function Modal({title,note,close,saving,onSubmit,children}:{title:string;note:string;close:()=>void;saving:boolean;onSubmit:(e:FormEvent)=>void;children:ReactNode}){
  return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><form className="modal wide-modal" onSubmit={onSubmit}><div className="modal-title"><div><h2>{title}</h2><p>{note}</p></div><button type="button" onClick={close}><X/></button></div><div className="form-grid">{children}</div><div className="modal-actions"><button type="button" onClick={close}>Hủy</button><button className="primary" disabled={saving}>{saving?'Đang lưu…':'Lưu thông tin'}</button></div></form></div>
}
