import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Home, Pencil, Plus, Search, UserPlus, Users, X } from 'lucide-react';
import { api } from './api';

type Building={id:number;name:string};
type Unit={id:number;buildingId:number;buildingName:string;code:string;status:'ACTIVE'|'INACTIVE'};
type Occupancy={id:number;unitId:number;unitCode:string;buildingId:number;buildingName:string;occupancyRole:'OWNER'|'TENANT'|'REPRESENTATIVE';startDate:string;endDate?:string;primary:boolean};
type Resident={id:number;customerCode:string;customerType:'INDIVIDUAL'|'ORGANIZATION';fullName:string;phone?:string;email?:string;taxCode?:string;birthYear?:number;gender?:'MALE'|'FEMALE'|'OTHER';nationalId?:string;active:boolean;occupancies:Occupancy[]};
const today=new Date().toISOString().slice(0,10);
const roleName={OWNER:'Chủ sở hữu',TENANT:'Người thuê',REPRESENTATIVE:'Đại diện'};
const genderName={MALE:'Nam',FEMALE:'Nữ',OTHER:'Khác'};

export function ResidentsPage(){
  const [buildings,setBuildings]=useState<Building[]>([]),[units,setUnits]=useState<Unit[]>([]),[residents,setResidents]=useState<Resident[]>([]);
  const [buildingId,setBuildingId]=useState(''),[keyword,setKeyword]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[saving,setSaving]=useState(false);
  const [editing,setEditing]=useState<Resident|null>(null),[assigning,setAssigning]=useState<Resident|null>(null);
  const [form,setForm]=useState({customerCode:'',customerType:'INDIVIDUAL',fullName:'',phone:'',email:'',taxCode:'',birthYear:'',gender:'',nationalId:'',active:true});
  const [assignment,setAssignment]=useState({unitId:'',occupancyRole:'OWNER',startDate:today,endDate:'',primary:true});

  async function loadResidents(){setLoading(true);setError('');try{const p=new URLSearchParams();if(buildingId)p.set('buildingId',buildingId);if(keyword.trim())p.set('keyword',keyword.trim());setResidents(await api<Resident[]>(`/residents${p.size?`?${p}`:''}`))}catch(e){setError(e instanceof Error?e.message:'Không tải được dữ liệu.')}finally{setLoading(false)}}
  useEffect(()=>{Promise.all([api<Building[]>('/buildings'),api<Unit[]>('/units')]).then(([b,u])=>{setBuildings(b);setUnits(u.filter(x=>x.status==='ACTIVE'))}).catch(e=>setError(e.message))},[]);
  useEffect(()=>{const t=setTimeout(loadResidents,250);return()=>clearTimeout(t)},[buildingId,keyword]);
  const stats=useMemo(()=>({total:residents.length,owners:residents.filter(r=>r.occupancies.some(o=>o.occupancyRole==='OWNER'&&!o.endDate)).length,unlinked:residents.filter(r=>!r.occupancies.some(o=>!o.endDate)).length}),[residents]);
  function openCreate(){setEditing({} as Resident);setForm({customerCode:'',customerType:'INDIVIDUAL',fullName:'',phone:'',email:'',taxCode:'',birthYear:'',gender:'',nationalId:'',active:true});setError('')}
  function openEdit(r:Resident){setEditing(r);setForm({customerCode:r.customerCode,customerType:r.customerType,fullName:r.fullName,phone:r.phone??'',email:r.email??'',taxCode:r.taxCode??'',birthYear:r.birthYear?.toString()??'',gender:r.gender??'',nationalId:r.nationalId??'',active:r.active});setError('')}
  function openAssign(r:Resident){const available=buildingId?units.filter(u=>String(u.buildingId)===buildingId):units;setAssigning(r);setAssignment({unitId:String(available[0]?.id??''),occupancyRole:'OWNER',startDate:today,endDate:'',primary:true});setError('')}
  async function submitResident(e:FormEvent){e.preventDefault();setSaving(true);setError('');try{const body={...form,birthYear:form.birthYear?Number(form.birthYear):null,gender:form.gender||null,nationalId:form.nationalId||null};if(editing?.id)await api(`/residents/${editing.id}`,{method:'PUT',body:JSON.stringify(body)});else await api('/residents',{method:'POST',body:JSON.stringify(body)});setEditing(null);await loadResidents()}catch(e){setError(e instanceof Error?e.message:'Không lưu được khách hàng.')}finally{setSaving(false)}}
  async function submitAssignment(e:FormEvent){e.preventDefault();if(!assigning)return;setSaving(true);setError('');try{await api(`/residents/${assigning.id}/occupancies`,{method:'POST',body:JSON.stringify({...assignment,unitId:Number(assignment.unitId),endDate:assignment.endDate||null})});setAssigning(null);await loadResidents()}catch(e){setError(e instanceof Error?e.message:'Không thể gán căn hộ.')}finally{setSaving(false)}}
  async function endLink(o:Occupancy){if(!confirm(`Chấm dứt liên kết với căn ${o.unitCode} từ hôm nay?`))return;try{await api(`/residents/occupancies/${o.id}`,{method:'DELETE'});await loadResidents()}catch(e){setError(e instanceof Error?e.message:'Không thể cập nhật.')}}

  return <>
    <header><div><h1>Cư dân và chủ căn hộ</h1><p>Quản lý người nộp phí và quan hệ sở hữu hoặc thuê căn hộ</p></div><button className="primary" onClick={openCreate}><UserPlus/>Thêm khách hàng</button></header>
    <section className="unit-summary"><article><Users/><span><b>{stats.total}</b><small>Khách hàng đang hiển thị</small></span></article><article><Home/><span><b>{stats.owners}</b><small>Chủ sở hữu căn hộ</small></span></article><article><span><b>{stats.unlinked}</b><small>Chưa liên kết căn hộ</small></span></article></section>
    <section className="panel unit-panel"><div className="toolbar"><select value={buildingId} onChange={e=>setBuildingId(e.target.value)}><option value="">Tất cả tòa</option>{buildings.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><label className="search"><Search/><input value={keyword} onChange={e=>setKeyword(e.target.value)} placeholder="Tên, mã hoặc số điện thoại..."/></label></div>{error&&<div className="page-error">{error}</div>}<div className="table-wrap"><table><thead><tr><th>Mã KH</th><th>Khách hàng</th><th>Liên hệ</th><th>Căn hộ đang liên kết</th><th>Trạng thái</th><th/></tr></thead><tbody>{loading?<tr><td colSpan={6} className="empty">Đang tải dữ liệu…</td></tr>:residents.length===0?<tr><td colSpan={6} className="empty">Chưa có dữ liệu cư dân hoặc chủ hộ.</td></tr>:residents.map(r=><tr key={r.id}><td><b>{r.customerCode}</b></td><td>{r.fullName}<small className="cell-note">{r.customerType==='INDIVIDUAL'?'Cá nhân':'Tổ chức'}{r.taxCode?` · MST ${r.taxCode}`:''}</small></td><td>{r.phone||'—'}<small className="cell-note">{r.email}</small></td><td><div className="occupancy-list">{r.occupancies.filter(o=>!o.endDate).map(o=><span className={o.primary?'occupancy primary':'occupancy'} key={o.id}>{o.buildingName} · {o.unitCode}<small>{roleName[o.occupancyRole]}{o.primary?' · Liên hệ chính':''}</small><button title="Chấm dứt liên kết" onClick={()=>endLink(o)}>×</button></span>)}{!r.occupancies.some(o=>!o.endDate)&&<em>Chưa gán căn</em>}</div></td><td><span className={`status ${r.active?'active':'inactive'}`}>{r.active?'Hoạt động':'Ngừng'}</span></td><td className="actions"><button title="Gán căn hộ" onClick={()=>openAssign(r)}><Plus/></button><button title="Sửa" onClick={()=>openEdit(r)}><Pencil/></button></td></tr>)}</tbody></table></div></section>

    {editing&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setEditing(null)}}><form className="modal wide-modal" onSubmit={submitResident}><div className="modal-title"><div><h2>{editing.id?'Cập nhật khách hàng':'Thêm cư dân/chủ hộ'}</h2><p>Các trường có dấu * bắt buộc khi khách hàng là chủ sở hữu.</p></div><button type="button" onClick={()=>setEditing(null)}><X/></button></div>{error&&<div className="login-error">{error}</div>}<div className="form-grid"><label>Mã khách hàng<input required maxLength={30} value={form.customerCode} onChange={e=>setForm({...form,customerCode:e.target.value})} placeholder="KH-0001"/></label><label>Loại khách hàng<select value={form.customerType} onChange={e=>setForm({...form,customerType:e.target.value})}><option value="INDIVIDUAL">Cá nhân</option><option value="ORGANIZATION">Tổ chức</option></select></label><label className="full">Họ tên/Tên tổ chức<input required maxLength={200} value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})}/></label><label>Số điện thoại *<input maxLength={30} value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Email<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label>{form.customerType==='INDIVIDUAL'&&<><label>Năm sinh *<input type="number" min="1900" max="2100" value={form.birthYear} onChange={e=>setForm({...form,birthYear:e.target.value})} placeholder="1985"/></label><label>Giới tính *<select value={form.gender} onChange={e=>setForm({...form,gender:e.target.value})}><option value="">Chọn giới tính</option><option value="MALE">Nam</option><option value="FEMALE">Nữ</option><option value="OTHER">Khác</option></select></label><label className="full">Căn cước công dân *<input inputMode="numeric" maxLength={12} pattern="[0-9]{12}" value={form.nationalId} onChange={e=>setForm({...form,nationalId:e.target.value.replace(/\D/g,'')})} placeholder="12 chữ số"/></label></>}{form.customerType==='ORGANIZATION'&&<label>Mã số thuế<input maxLength={30} value={form.taxCode} onChange={e=>setForm({...form,taxCode:e.target.value})}/></label>}{editing.id&&<label>Trạng thái<select value={form.active?'true':'false'} onChange={e=>setForm({...form,active:e.target.value==='true'})}><option value="true">Hoạt động</option><option value="false">Ngừng hoạt động</option></select></label>}</div><div className="modal-actions"><button type="button" onClick={()=>setEditing(null)}>Hủy</button><button className="primary" disabled={saving}>{saving?'Đang lưu…':'Lưu thông tin'}</button></div></form></div>}

    {assigning&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setAssigning(null)}}><form className="modal" onSubmit={submitAssignment}><div className="modal-title"><div><h2>Gán căn hộ</h2><p>{assigning.fullName} — chọn căn và vai trò sử dụng.</p></div><button type="button" onClick={()=>setAssigning(null)}><X/></button></div>{error&&<div className="login-error">{error}</div>}<div className="form-grid"><label>Căn hộ<select required value={assignment.unitId} onChange={e=>setAssignment({...assignment,unitId:e.target.value})}><option value="" disabled>Chọn căn hộ</option>{units.filter(u=>!buildingId||String(u.buildingId)===buildingId).map(u=><option key={u.id} value={u.id}>{u.buildingName} · {u.code}</option>)}</select></label><label>Vai trò<select value={assignment.occupancyRole} onChange={e=>setAssignment({...assignment,occupancyRole:e.target.value})}><option value="OWNER">Chủ sở hữu</option><option value="TENANT">Người thuê</option><option value="REPRESENTATIVE">Người đại diện</option></select></label><label>Ngày bắt đầu<input required type="date" value={assignment.startDate} onChange={e=>setAssignment({...assignment,startDate:e.target.value})}/></label><label>Ngày kết thúc (nếu có)<input type="date" value={assignment.endDate} onChange={e=>setAssignment({...assignment,endDate:e.target.value})}/></label><label className="check-label full"><input type="checkbox" checked={assignment.primary} onChange={e=>setAssignment({...assignment,primary:e.target.checked})}/> Đặt làm người liên hệ và chịu phí chính của căn hộ</label></div><div className="modal-actions"><button type="button" onClick={()=>setAssigning(null)}>Hủy</button><button className="primary" disabled={saving||!assignment.unitId}>{saving?'Đang lưu…':'Gán căn hộ'}</button></div></form></div>}
  </>;
}
