import { FormEvent, useEffect, useState } from 'react';
import { Plus, RefreshCw, X } from 'lucide-react';
import { api } from './api';
type Unit={id:number;code:string;buildingName:string;areaM2:number|null}; type Person={name:string;phone:string;birthYear?:number;nationalId?:string;role:string}; type Service={id:number;serviceName:string;variant?:string;quantity:number;unitPrice:number;collectionMode:string;licensePlate?:string;electricVehicle:boolean;mandatory:boolean;estimatedAmount:number}; type Profile={occupants:Person[];services:Service[]};
const today=new Date().toISOString().slice(0,10),money=(n:number)=>new Intl.NumberFormat('vi-VN').format(n)+' đ';
const options=[['PARKING_MONTHLY','Gửi xe','Xe đạp'],['PARKING_MONTHLY','Gửi xe','Xe máy'],['PARKING_MONTHLY','Gửi xe','Ô tô'],['INTERNET','Internet',''],['ELECTRICITY','Điện',''],['WATER','Nước','']];
export function UnitProfileModal({unit,close}:{unit:Unit;close:()=>void}){const [data,setData]=useState<Profile|null>(null),[mode,setMode]=useState<'view'|'owner'|'service'>('view'),[error,setError]=useState(''),[saving,setSaving]=useState(false);const [owner,setOwner]=useState({customerCode:'',fullName:'',phone:'',birthYear:'',gender:'MALE',nationalId:'',effectiveDate:today});const [service,setService]=useState({option:'0',quantity:'1',unitPrice:'0',collectionMode:'MANAGEMENT',startDate:today,licensePlate:'',electricVehicle:false});
async function load(){try{setData(await api<Profile>(`/unit-profiles/${unit.id}`));setError('')}catch(e){setError(e instanceof Error?e.message:'Không tải được hồ sơ.')}}useEffect(()=>{load()},[unit.id]);const currentOwner=data?.occupants.find(x=>x.role==='OWNER');
async function saveOwner(e:FormEvent){e.preventDefault();setSaving(true);try{await api(`/unit-profiles/${unit.id}/owner`,{method:'POST',body:JSON.stringify({...owner,birthYear:Number(owner.birthYear)})});setMode('view');await load()}catch(e){setError(e instanceof Error?e.message:'Không lưu được chủ hộ.')}finally{setSaving(false)}}
async function saveService(e:FormEvent){e.preventDefault();setSaving(true);try{const [serviceCode,serviceName,variant]=options[Number(service.option)];await api(`/unit-profiles/${unit.id}/services`,{method:'POST',body:JSON.stringify({serviceCode,serviceName,variant:variant||null,chargeMethod:'FIXED',quantity:Number(service.quantity),unitPrice:Number(service.unitPrice),collectionMode:service.collectionMode,startDate:service.startDate,licensePlate:serviceCode==='PARKING_MONTHLY'?service.licensePlate:null,electricVehicle:serviceCode==='PARKING_MONTHLY'&&service.electricVehicle})});setMode('view');await load()}catch(e){setError(e instanceof Error?e.message:'Không gán được dịch vụ.')}finally{setSaving(false)}}
return <div className="modal-backdrop"><div className="modal profile-modal"><div className="modal-title"><div><h2>Hồ sơ căn hộ {unit.code}</h2><p>{unit.buildingName} · {unit.areaM2} m²</p></div><button onClick={close}><X/></button></div>{error&&<div className="login-error">{error}</div>}{mode==='view'&&<><div className="profile-heading"><h3>Chủ hộ bắt buộc</h3><button className="secondary" onClick={()=>setMode('owner')}><RefreshCw/>{currentOwner?'Thay đổi chủ hộ':'Gán chủ hộ'}</button></div>{currentOwner?<div className="owner-card"><b>{currentOwner.name}</b><span>{currentOwner.phone}</span><small>Sinh năm {currentOwner.birthYear} · CCCD {currentOwner.nationalId}</small></div>:<div className="profile-warning">Chưa có chủ hộ.</div>}<div className="profile-heading"><h3>Dịch vụ căn hộ</h3><button className="secondary" onClick={()=>setMode('service')}><Plus/>Gán dịch vụ</button></div><div className="service-cards">{data?.services.map(s=><article key={s.id}><div><b>{s.serviceName}{s.variant?` · ${s.variant}`:''}{s.electricVehicle?' · Xe điện':''}</b><small>{s.licensePlate?`Biển số ${s.licensePlate} · `:''}{s.quantity} × {money(s.unitPrice)} · {s.collectionMode==='MANAGEMENT'?'BQL thu':'Nhà cung cấp thu'}</small></div><strong>{money(s.estimatedAmount)}</strong>{s.mandatory&&<em>Bắt buộc</em>}</article>)}</div></>}
{mode==='owner'&&<form onSubmit={saveOwner}><div className="form-grid"><label>Mã khách hàng<input required value={owner.customerCode} onChange={e=>setOwner({...owner,customerCode:e.target.value})}/></label><label>Ngày hiệu lực<input required type="date" value={owner.effectiveDate} onChange={e=>setOwner({...owner,effectiveDate:e.target.value})}/></label><label className="full">Họ tên<input required value={owner.fullName} onChange={e=>setOwner({...owner,fullName:e.target.value})}/></label><label>Số điện thoại<input required value={owner.phone} onChange={e=>setOwner({...owner,phone:e.target.value})}/></label><label>Năm sinh<input required type="number" min="1900" max="2100" value={owner.birthYear} onChange={e=>setOwner({...owner,birthYear:e.target.value})}/></label><label>Giới tính<select value={owner.gender} onChange={e=>setOwner({...owner,gender:e.target.value})}><option value="MALE">Nam</option><option value="FEMALE">Nữ</option><option value="OTHER">Khác</option></select></label><label>CCCD<input required pattern="[0-9]{12}" maxLength={12} value={owner.nationalId} onChange={e=>setOwner({...owner,nationalId:e.target.value.replace(/\D/g,'')})}/></label></div><Actions cancel={()=>setMode('view')} saving={saving}/></form>}
{mode==='service'&&<form onSubmit={saveService}><div className="form-grid"><label className="full">Dịch vụ<select value={service.option} onChange={e=>{const option=e.target.value;setService({...service,option,collectionMode:Number(option)>=3?'PROVIDER':'MANAGEMENT',licensePlate:'',electricVehicle:false})}}>{options.map((x,i)=><option key={i} value={i}>{x[1]}{x[2]?` – ${x[2]}`:''}</option>)}</select></label>{Number(service.option)<3&&<><label>Biển số xe{Number(service.option)>0?' *':''}<input required={Number(service.option)>0} maxLength={20} value={service.licensePlate} onChange={e=>setService({...service,licensePlate:e.target.value.toUpperCase()})} placeholder={Number(service.option)===2?'30A-123.45':'29X1-123.45'}/></label><label className="check-label"><input type="checkbox" checked={service.electricVehicle} onChange={e=>setService({...service,electricVehicle:e.target.checked})}/> Là xe điện</label></>}<label>Số lượng<input required type="number" min="0.001" step="0.001" value={service.quantity} onChange={e=>setService({...service,quantity:e.target.value})}/></label><label>Đơn giá<input required type="number" min="0" value={service.unitPrice} onChange={e=>setService({...service,unitPrice:e.target.value})}/></label><label>Đơn vị thu<select value={service.collectionMode} onChange={e=>setService({...service,collectionMode:e.target.value})}><option value="MANAGEMENT">Ban quản lý thu</option><option value="PROVIDER">Nhà cung cấp thu</option></select></label><label>Ngày bắt đầu<input required type="date" value={service.startDate} onChange={e=>setService({...service,startDate:e.target.value})}/></label></div><Actions cancel={()=>setMode('view')} saving={saving}/></form>}</div></div>}
function Actions({cancel,saving}:{cancel:()=>void;saving:boolean}){return <div className="modal-actions"><button type="button" onClick={cancel}>Quay lại</button><button className="primary" disabled={saving}>{saving?'Đang lưu…':'Lưu thông tin'}</button></div>}
